### ISSUE TITLE
Support for Repeatable Fields

### ISSUE THREAD

**Issue by bryceadams** [mustardBees/cmb-field-select2#10]
When select2 is cloned, there are issues with the data saving. Discussed here and a bit related - https://github.com/humanmade/Custom-Meta-Boxes/issues/73

Can test by using a `pw_select` type in a repeatable group field.

**Comment by monecchi** [comment]
Hey @bryceadams! How about passing a function which returns an array of options for the field? I've dowloaded your forked version of the cmb-field-select2 and got it working (almost).

I'm using the select2 field within a CMB2 repeatable group, and although it renders the field with my function, that returns an array of woocommerce variable products, it does not seem to be saving any values.

It surprisingly works if I set up a CMB2 default select field, and then pass the function to it. By doing that, I end up with a properly populated select field with the product variations and their ID's as the value of each `<option>` element.

However, when I try to set up the `'type' => 'pw_select'`, it fails on saving the values.

Any chances my function is causing the issue? Here it is.

    function get_product_variation_term_options( $query_args ) {

    global $post, $product;

    $args = wp_parse_args( $query_args, array(
		'post_type'   => 'product_variation',
		'post_status' => array( 'private', 'publish' ),
		'posts_per_page' => -1,
		'orderby'     => 'menu_order',
		'order'       => 'ASC',
		'post_parent' => get_related_post_id() // external function that gets the post ID
    ) );

    $post_options = array();

    // return post type as options
    $posts = get_posts( $args );

	if ( $posts ) {
     	foreach ( $posts as $post ) {

     	$variation = wc_get_product($post);

        $post_options[ $post->ID ] = $variation->get_formatted_name();
     	}
	}
	    return $post_options;
	}

And here's the field set up:

        $cmb_group->add_group_field( $group_field_id, array(
            'name' => __( 'Display a Buy Button?', 'pivot' ),
            'class'   => 'cmb-type-pw-select select2', // cmb2_select default class
            'desc' => __( 'Select a product variation ', 'mytheme'),
            'id' => 'select_post_type_variations',
            'type' => 'pw_select',
            'options' => get_product_variation_term_options( array( 'post_type' => 'product_variation', 'posts_per_page' => 4 ) ), 
        ) );

**Comment by AlchemyUnited** [comment]
@monecchi - I'm a bit backed up atm but if you want me to take a swing at it let me know and we'll figure out how to pass your fork over to me.

**Comment by monecchi** [comment]
Thanks @AlchemyUnited. I'd really appreciate it!

I've tried a few different cmb-field-select2 forks, as a few others select2 field types for CMB2, but all those expects an array of options to be manually set such as `'options' => array( '1' => 'one', '2' => 'two' ),` while I was hoping to populate the options array with a function. 

Anyway, no rush for this though, I've decided to fallback to CMB2 default select field until I could get it solved.

Regards.

**Comment by AlchemyUnited** [comment]
@monecchi - Okay. But this sounds like a challenge. And a useful one if solved. Where is your fork? Or maybe I'll give it a fresh crack and then we've can trade notes?

**Comment by mustardBees** [comment]
@AlchemyUnited @monecchi A massive thanks to @AlchemyUnited for the repeatable field work. It took a while to get around to looking at this in detail. I've [pushed a new release ](https://github.com/mustardBees/cmb-field-select2/releases) which incorporates this work.

I'd appreciate any assistance testing this across more sites. It has worked well for me with the exception of a couple of issues which I've noted in a known issues/limitations section in the documentation.

**Comment by monecchi** [comment]
Hey @mustardBees, thank you so much for pushing the new version. I can confirm it works beautifully now! No issues with my query/get_posts function so far. @AlchemyUnited thank you for your great contribution with the repeatable field work. You guys rock!!!

![funny-gif-happy-clapping-computer](https://cloud.githubusercontent.com/assets/5252519/15556368/ee27e4ca-22a3-11e6-9c12-aa36d9cabdb3.gif)
