### ISSUE TITLE
Select2 ajax option, is possible? How?

### ISSUE THREAD

**Issue by paquitodev** [mustardBees/cmb-field-select2#14]
I want to use this plugin for get a list of all post (32 000 by now) on my WP, get all them from one shot takes to long so I'm asking if it's possible to use Ajax functionality on this plugin and how to, any advice?

**Comment by mustardBees** [comment]
This isn't part of the existing plugin but it's definitely something I've thought about.

I noticed @jtsternberg wrote an interesting field, [CMB2 Post Search field](https://github.com/WebDevStudios/CMB2-Post-Search-field). I've not had chance to play with it, but it sounds like it might solve your problem.
