### ISSUE TITLE
Support for custom path/url

### ISSUE THREAD

**Issue by kalicki** [mustardBees/cmb-field-select2#16]
```php
if ( ! defined( 'PW_SELECT2_URL' ) ) {
	define( 'PW_SELECT2_URL', plugin_dir_url( __FILE__ ) );
}
```

It would be interesting to put a validation because I can customize the URL

**Comment by mustardBees** [comment]
This is great suggestion. I will be refactoring the code over the next few weeks. It'll likely end up as a filter.

**Comment by mustardBees** [comment]
Hi @kalicki. I've released [a new version](https://github.com/mustardBees/cmb-field-select2/releases). There is a filter which can be used to override the asset path. I've given an [example over here](https://gist.github.com/mustardBees/aa32a7667af470e9d7e95d4caa8e4123). I'd also appreciate it if you could generally have a play with the new release and open an issue if you have any trouble.
