### ISSUE TITLE
Dashes in field id breaks JS

### ISSUE THREAD

**Issue by gyrus** [mustardBees/cmb-field-select2#18]
If dashes are used in the ID of a field set to type `pw_multiselect`, the JavaScript output for the field breaks because dashes aren't valid in JS var names. Maybe escape the field ID when using it as the JS var name?

**Comment by mustardBees** [comment]
Hi @gyrus. I've released [a new version](https://github.com/mustardBees/cmb-field-select2/releases). This should be resolved. I'd also appreciate it if you could generally have a play with the new release!
