### ISSUE TITLE
pw_select data not saving

### ISSUE THREAD

**Issue by wilson1000** [mustardBees/cmb-field-select2#22]
Hi,

I've included your library as an addition to an application I'm creating for a client. The app is advanced but uses the WP ecosystem to manage data and present to end users.

All meta boxes produced by CMB2 are working really well. Would you have any idea why your custom field type is being ignored by the save process?

Many thanks,
Damien

**Comment by wilson1000** [comment]
OK,

I was associating a post with another post. Turns out I needed to pass the post ID as the key name in options:

`$post_options[ $post->ID ] = $post->post_title;`

I was in fact passing the post name before. Doh!

Damien

**Comment by mustardBees** [comment]
Glad you got this sorted! :)
