### ISSUE TITLE
Add a composer.json file to allow people to use composer to include this add-on

### ISSUE THREAD

**Issue by richardtape** [mustardBees/cmb-field-select2#28]
I've opened a PR for this: https://github.com/mustardBees/cmb-field-select2/pull/27

For folks who wish to use this;

1. Add a vcs `type` repository with `url` of https://github.com/mustardBees/cmb-field-select2 to your repositories array in your project's composer.json file
2. add "mustardBees/cmb-field-select2": "dev-master" (or a specific version number) to your `require` object in your project's composer.json file
3. (optional) if you're autoloading, add "vendor/mustardBees/cmb-field-select2/cmb-field-select2.php" to your `files` array within the `autoload` object in your project's composer.json file.

**Comment by mustardBees** [comment]
Thanks @richardtape!
