### ISSUE TITLE
Reordering groups doesn't reorder select fields (until you update)

### ISSUE THREAD

**Issue by tahninial** [mustardBees/cmb-field-select2#29]
There have been problems with select2 and groups in the past (see - [https://github.com/mustardBees/cmb-field-select2/issues/10](https://github.com/mustardBees/cmb-field-select2/issues/10) - it might be linked but I didn't want to piggyback) but I think there might now be an additional aspect to this that wasn't happening before. 

I am sure in the past I could reorder the groups and the select would travel with it, but now if I move my top group to the bottom, the select2 fields stay in the same order, ~~which essentially means I am jumbling up my metadata~~ **edit:** which makes it seem like you're ruining your metadata until you save changes.

I have seen from the thread linked above that a destroy and init when these thing are triggered could solve matters but I sadly haven't been able to get my head around how to use the CMB2 before/after events to destroy and re-enable the select2. I get the principle of it but I can't quite get my head around how to have one trigger the other besides seeing that events exist in the CMB2 code..!

If someone could point me in the right direction that would be a massive help please as it would be amazing to be able to keep using this awesome addition to the framework but it's making my client understandably nervous!

**Comment by tahninial** [comment]
Edit: I just tested this in a dev environment and realised that the meta doesn't jumble when you save it it just appears to not move with the group, so same problem/fix but doesn't break the site as my client was reporting

**Comment by mustardBees** [comment]
@tahninial I've pushed a [new release](https://github.com/mustardBees/cmb-field-select2/releases) which supports repeatable groups. It also supports the reordering of rows. Can you take a look and generally have a play with the release. Let me know if you have any trouble.

**Comment by tahninial** [comment]
Thanks, no issues from me - it works great
