### ISSUE TITLE
Not able To create blank as default value

### ISSUE THREAD

**Issue by jeni1616** [mustardBees/cmb-field-select2#36]
Thank you for this great plugin , i tried messing with custom code like allowClear: true, placeholder: {id: "-1",}

but no matter what when i update post , it just take first value of array as default , i want to keep it blank , but it's selecting to first value of array as default value , is there any option i can set blank field till user not select anything manually ?

Thanks .

**Comment by jeni1616** [comment]
i also tried this when creating field : 

'attributes' => array(
				'data-allowClear' => true,
				'data-placeholder--text' => 'sme',
				'data-placeholder--id' => '-1',
			),

but throwing error in console :  Cannot use 'in' operator to search for 'text' in
and select2 also stop work after that .

Thanks.

**Comment by jeni1616** [comment]
don't know why but it's working now without any change ! 😀 
may be issue was in my array itself , i just made first entry with value -1 .
Thank you .

**Comment by mustardBees** [comment]
@jeni1616 Glad you got this sorted.
