### ISSUE TITLE
Optgroup 

### ISSUE THREAD

**Issue by Surgeonito** [mustardBees/cmb-field-select2#37]
I did <optgroup> management, but didn't test it back and forth. 
Are you planning to add something similar?

**Comment by mustardBees** [comment]
@Surgeonito It's not something I'd considered adding. I'd love to see your implementation.

**Comment by Surgeonito** [comment]
;)
I'm lazy too...
here, this is only one method I've altered:
`public function get_pw_multiselect_options( $field_escaped_value = array(), $field_type_object ) {
		$options = (array) $field_type_object->field->options();

		// If we have selected items, we need to preserve their order
		if ( ! empty( $field_escaped_value ) ) {
			$options = $this->sort_array_by_array( $options, $field_escaped_value );
		}

		$selected_items = '';
		$other_items = '';

		foreach ( $options as $option_value => $option_label ) {

			if( is_array($option_label) ){
				$selected_items .= '<optgroup label="'.$option_value.'">';
				foreach( $option_label as $val=>$labl){
					// Clone args & modify for just this item
					$option = array(
						'value' => $val,
						'label' => $labl,
					);

					// Split options into those which are selected and the rest
					if ( in_array( $val, (array) $field_escaped_value ) ) {
						$option['checked'] = true;
						$selected_items .= $field_type_object->select_option( $option );
					} else {
						$selected_items .= $field_type_object->select_option( $option );
					}
				}
				$selected_items .= '</optgroup>';
			}else{
				// Clone args & modify for just this item
				$option = array(
					'value' => $option_value,
					'label' => $option_label,
				);

				// Split options into those which are selected and the rest
				if ( in_array( $option_value, (array) $field_escaped_value ) ) {
					$option['checked'] = true;
					$selected_items .= $field_type_object->select_option( $option );
				} else {
					$other_items .= $field_type_object->select_option( $option );
				}
			}


		}

		return $selected_items . $other_items;
	}`
