### ISSUE TITLE
Maximum selection length not working

### ISSUE THREAD

**Issue by stompweb** [mustardBees/cmb-field-select2#39]
I have tried this with the example code and I am able to pick more than 3 items:

```php
$cmb->add_field( array(
	'name'       => 'Ingredients',
	'id'         => $prefix . 'ingredients',
	'desc'       => 'Select ingredients. Drag to reorder.',
	'type'       => 'pw_multiselect',
	'options'    => array(
		'flour'  => 'Flour',
		'salt'   => 'Salt',
		'eggs'   => 'Eggs',
		'milk'   => 'Milk',
		'butter' => 'Butter',
	),
	'attributes' => array(
		'data-maximum-selection-length' => '2',
	),
) );
```

I have tried it without the quotes around the single quotes around the '2' as well and it doesn't work either.

**Comment by stompweb** [comment]
Not sure why the code is all in a block like it is but I am basically using the example from the readme

**Comment by stompweb** [comment]
Hi @mustardBees, just wondered if you've seen this and can replicate it. Let me know if you want to test anything else out on this.

**Comment by mustardBees** [comment]
Hi @stompweb. I've tested your field code with v3.0.3 of this field against CMB2 2.2.2.1. The maximum selection appears to be working as expected.

It's possible you have another plugin installed which is loading an older version of the Select2 JavaScript. I've seen this cause issues in the past. Worth checking the source view of the admin page with this field on.

Let me know how you get on.
