### ISSUE TITLE
Does not work when the options are taxonomies 

### ISSUE THREAD

**Issue by hookedonweb** [mustardBees/cmb-field-select2#40]
A taxonomy attribute would be nice.

**Comment by hookedonweb** [comment]
Did not see the terms links at the bottom of the page. Word perfectly.

**Comment by mustardBees** [comment]
@hookedonweb Just a quick note. Currently this field does not support the setting of an object's terms. This field will work well if your intention is to save a term ID/an array of term IDs as post meta.
