### ISSUE TITLE
Sortable not being saved

### ISSUE THREAD

**Issue by allysonsouza** [mustardBees/cmb-field-select2#43]
Hi, firstly, thanks for the great additional field for CMB!

I'm just having problem with the sortable feature of Select2, it's not being saved. When I save as a draft the options come back to their original order. Can you help me with this?

**Comment by mustardBees** [comment]
@allysonsouza Can you confirm the version of CMB2 and of this field?

**Comment by allysonsouza** [comment]
@mustardBees I'm using `CMB2 2.2.5.3`, and the latest release of CMB2 Field Select2 (downloaded yesterday).

**Comment by mustardBees** [comment]
Just tested that combination. I have a meta box associated with a post type. I tried adding a new post and selected a number of items, reordered the list and hit Save Draft.

Seems to be working over here. Possibly you have a different meta box setup? Or a conflict somewhere, do you have any console errors?

**Comment by allysonsouza** [comment]
Sorry man, your plugin is working really well, my bad code that is broken.
I was putting a whitespace before the options array keys (I don't know why) and that's the problem.

Thanks for the fast reply and for the great job!

**Comment by mustardBees** [comment]
@allysonsouza No worries. Enjoy!
