### ISSUE TITLE
Double checking on whether terms can be returned or just numeric arrays for tags/categories

### ISSUE THREAD

**Issue by investreads** [mustardBees/cmb-field-select2#45]
I think you may have already alluded to this in previous questions, but I wanted to confirm that you can't currently return the taxonomy term in post metadata. You can only return the term ID.

I spent a ton of time trying to troubleshoot this, and finally saw it mentioned in an answer to a question from a couple years back.

All I'm currently get returned is a numeric array. I can't get an associative term array returned (in a single post where it is a CPT and a custom taxonomy).

**Comment by mustardBees** [comment]
That’s correct. This field type stores the select value(s) in post meta.

You would need to write additional code to relate the object with your term(s).

**Comment by investreads** [comment]
Like the deft WordPress/php ninja I am, I figured this shit out like a boss. How you do it is below, for future generations to bask in my Wordpress/php glory.

`` $values = get_post_meta( get_the_ID(), 'CMB_field', true ); foreach ($values as $value) { $term = get_term_by('term_id', $value, 'taxonomy'); $name = $term->name; echo $name;}``

Or to separate by commas 

`$values = get_post_meta( get_the_ID(), 'CMB_field', true ); $total = count($values);$i=0;
foreach ($values as $value) {$i++; $term = get_term_by('term_id', $value, 'keywords'); $name = $term->name; echo $name; if($i !=$total) echo', ';}`

**Comment by mustardBees** [comment]
Nice work! Glad you got this sorted.
